; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1_mini_ota]
platform = espressif8266@4.2.1
board = d1_mini
framework = arduino
extends = env:d1_mini
upload_protocol = espota
upload_port = 192.168.100.38
lib_deps =
    majicdesigns/MD_Parola @ ^3.7.5
    adafruit/DHT sensor library @ ^1.4.7
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    bblanchon/ArduinoJson @ ^6.21.5
    shurillu/CTBot @ ^2.1.14

; Локальная библиотека для погоды
lib_extra_dirs =
    lib

; Мониторинг памяти
build_flags =
    -DCORE_DEBUG_LEVEL=0
